project_name: influxdb
builds:
  - id: influx
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6

    main: ./cmd/influx/
    flags:
      - -tags={{if and (eq .Os "linux") (eq .Arch "amd64")}}osusergo,netgo,static_build{{end}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=xcc
      - PKG_CONFIG=$GOPATH/bin/pkg-config
      - MACOSX_DEPLOYMENT_TARGET=10.11
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} {{if and (eq .Os "linux") (eq .Arch "amd64")}}-extldflags "-fno-PIC -static -Wl,-z,stack-size=8388608"{{end}}
    binary: influx

  - id: influxd
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6

    main: ./cmd/influxd/
    flags:
      - -tags=assets{{if and (eq .Os "linux") (eq .Arch "amd64")}},osusergo,netgo,static_build{{end}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=xcc
      - PKG_CONFIG=$GOPATH/bin/pkg-config
      - MACOSX_DEPLOYMENT_TARGET=10.11
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} {{if and (eq .Os "linux") (eq .Arch "amd64")}}-extldflags "-fno-PIC -static -Wl,-z,stack-size=8388608"{{end}}
    binary: influxd
    hooks:
      pre: make generate

snapshot:
  name_template: 9.9.9

signs:
  -
    signature: "${artifact}.asc"
    cmd: gpg
    args: [ "--passphrase", "{{.Env.PASSPHRASE}}",  "--pinentry-mode=loopback", "--batch", "--armor",  "--detach-sign", "${artifact}"]
    artifacts: all

nfpms:
  -
    id: "influxdata"
    builds: ["influx", "influxd"]
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    files:
      "scripts/init.sh": "/usr/lib/influxdb/scripts/init.sh"
      "scripts/influxdb.service": "/usr/lib/influxdb/scripts/influxdb.service"
      "scripts/logrotate": "/etc/logrotate.d/influxdb"
    scripts:
      preinstall:  "scripts/pre-install.sh"
      postinstall: "scripts/post-install.sh"
      postremove: "scripts/post-uninstall.sh"
    overrides:
      rpm:
        replacements:
          amd64: x86_64
        file_name_template: "influxdb-{{ .Version }}.{{ .Arch }}{{if .Arm}}{{ if eq .Arm \"5\" }}el{{end}}{{ end }}{{if .Arm}}{{ if eq .Arm \"6\" }}hf{{end}}{{ end }}"
      deb:
       file_name_template: "influxdb_{{ .Version }}_{{ .Arch }}{{if .Arm}}{{ if eq .Arm \"5\" }}el{{end}}{{ end }}{{if .Arm}}{{ if eq .Arm \"6\" }}hf{{end}}{{ end }}"
    vendor: InfluxData
    homepage: https://influxdata.com
    maintainer: support@influxdb.com
    description: Distributed time-series database.
    license: Proprietary

blobs:
  - provider: "s3"
    bucket: "dl.influxdata.com"
    region: "us-east-1"
    folder: "influxdb/releases/"

archives:
  - id: influxdb_client
    builds: ["influx"]
    format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "influxdb_client_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{if .Arm}}{{ if eq .Arm \"5\" }}el{{end}}{{ end }}{{if .Arm}}{{ if eq .Arm \"6\" }}hf{{end}}{{ end }}"
    files:
      - LICENSE
      - README.md
  - id: influxdb_single_binary
    format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "influxdb-{{ .Version }}_{{ .Os }}_{{ .Arch }}{{if .Arm}}{{ if eq .Arm \"5\" }}el{{end}}{{ end }}{{if .Arm}}{{ if eq .Arm \"6\" }}hf{{end}}{{ end }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "influxdb_{{ .Version }}.sha256"
  algorithm: sha256

# Do not make github release
release:
  name_template: "v{{.Version}}"
  prerelease: auto # when we go to GA remove this line
  draft: false # This needs to be false, or the container image will not be published
  disable: true # we keep the artifacts in S3 and link from the website
